language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
# command to install dependencies
# install: "pip install foo bar --use-mirrors"
install: pip install coverage --use-mirrors
# command to run tests
# Require 100% coverage to pass tests
script:
- set -o pipefail
- nosetests --with-doctest --with-coverage 2>&1 | tee /dev/stderr | grep '^TOTAL.*100%' > /dev/null
notifications:
  email: false
