language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

# command to install dependencies
install:
    - pip install coverage --use-mirrors
    - pip install coveralls --use-mirrors

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
    - coverage run --source=toolz $(which nosetests) --with-doctest
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coverage report --show-missing --fail-under=100 ; fi

# load coverage status to https://coveralls.io
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coveralls ; fi

notifications:
  email: false
